export const reactNativeChapters = [
  "Introdução ao React Native",
  "O que é React Native?",
  "Instalação do React Native",
  "Configuração do Ambiente de Desenvolvimento",
  "Criando um Novo Projeto React Native com Expo",
  "Estrutura de Pastas no React Native com Atomic Design e Feature Sliced Design",
  "Diferenças entre React e React Native",
  "Componentes Básicos no React Native",
  "Utilizando o componente View",
  "Trabalhando com Text",
  "Componentes de Imagem no React Native",
  "Estilos no React Native",
  "Flexbox no React Native",
  "Posicionamento de Componentes",
  "Uso de ScrollView",
  "FlatList: Listas Performáticas",
  "Seções em Listas: SectionList",
  "Botões no React Native",
  "Input de Texto com TextInput",
  "Manipulando Inputs",
  "Tratamento de Eventos",
  "Componentes Controlados e Não Controlados",
  "State e Props no React Native",
  "Hook useState",
  "Hook useEffect",
  "Context API no React Native",
  "Navegação com React Navigation",
  "Stack Navigator",
  "Tab Navigator",
  "Drawer Navigator",
  "Navegação aninhada",
  "Passando parâmetros entre telas",
  "React Query no React Native",
  "Hooks personalizados",
  "Animações Básicas",
  "Animando Componentes com Animated",
  "Animando Layouts com LayoutAnimation",
  "Touchables no React Native",
  "Acessando APIs com Fetch",
  "Uso de Axios para Requisições HTTP",
  "Consumindo APIs REST",
  "Autenticação com JWT",
  "Protegendo Rotas no React Native",
  "Autenticação Biométrica",
  "Trabalhando com Mapas",
  "Geolocalização no React Native",
  "Integração com Google Maps",
  "Renderizando Mapas com react-native-maps",
  "Exibindo Pins e Marcadores no Mapa",
  "Calculando Rotas com Google Maps API",
  "Leitura de Códigos QR",
  "Usando a API de Sensores",
  "Integração com Acelerômetro",
  "Trabalhando com Giroscópio",
  "Vibração do Dispositivo",
  "Uso de Audio e Video no React Native",
  "Gravação de Áudio",
  "Reprodução de Vídeos",
  "Integração com WebSocket",
  "Criando um Chat com React Native",
  "Uso de Context API para Chat",
  "Integração com Firebase para Real-time",
  "Construção de UIs Responsivas",
  "Uso de Dimensions e Media Queries",
  "Uso de Platform API",
  "Integração com WebView",
  "Carregando Páginas Web no App",
  "Deep Linking para Web e App",
  "Uso de Fastlane para Automação de Deploy",
  "Otimização de Listas com FlatList",
  "Memoization com React.memo",
  "Uso do useCallback e useMemo",
  "Lazy Loading de Componentes",
  "Uso de Hooks Avançados",
  "Customização de Componentes Nativos",
  "Integração com Módulos Nativos",
  "Transição de Expo para React Native CLI",
  "Configuração de Tipografia",
  "Acessibilidade no React Native",
  "Internacionalização e Localização",
  "Tradução de Apps com react-i18next",
  "Temas Dinâmicos no React Native",
  "Modo Escuro e Modo Claro",
  "Uso de Lottie para Animações",
  "Análises de Uso com Firebase Analytics",
  "Estratégias de Monetização",
  "Publicidade no App com AdMob",
  "Implementação de Recursos Offline",
  "Sincronização de Dados Offline",
  "Detecção de Conectividade",
  "Uso de AppState para Gerenciar Estados",
  "Otimização de Consumo de Bateria",
  "Automação de Build e Testes",
  "Uso de CI/CD com GitHub Actions",
  "Automação de Build com Bitrise",
  "Melhores Práticas de Versionamento",
  "Manutenção de Apps em Produção",
];
const dialogflow = [
  "Introdução ao Dialogflow",
  "O que é um chatbot?",
  "Criando o primeiro agente",
  "Entendendo as Intenções",
  "Configurando entidades personalizadas",
  "Ajustes básicos de treinamento",
  "Como Dialogflow processa linguagem natural",
  "Adicionando respostas de texto",
  "Testando seu chatbot",
  "Exportando e importando agentes",
  "Integrando o Dialogflow ao Google Assistant",
  "Usando APIs do Dialogflow",
  "Gerenciando sessões de usuário",
  "Utilizando contextos em conversas",
  "Respostas dinâmicas com variáveis",
  "Detecção de idioma no Dialogflow",
  "Melhorando a experiência do usuário",
  "Reconhecimento de voz com Dialogflow",
  "Respostas baseadas em parâmetros",
  "Conectando o Dialogflow com serviços externos",
  "Como criar fluxos de conversa complexos",
  "Respostas condicionais no Dialogflow",
  "Uso avançado de entidades no Dialogflow",
  "Usando rich media nas respostas",
  "Gerenciamento de múltiplos agentes",
  "Analisando logs e relatórios no Dialogflow",
  "Integração com plataformas de chat",
  "Otimizando o tempo de resposta do chatbot",
  "Configurações de fallback e intents padrão",
  "Como lidar com perguntas inesperadas",
  "Conectando Dialogflow com uma API externa",
  "Treinando agentes para múltiplos idiomas",
  "Como criar pequenas conversas casuais",
  "Melhorando a precisão das intenções",
  "Como gerenciar diálogos complexos",
  "Respostas personalizadas com fulfillment",
  "Acessando APIs através do fulfillment",
  "Criando chatbots para sites",
  "Gerenciamento de permissões e segurança",
  "Como criar interações proativas",
  "Aplicando Machine Learning ao Dialogflow",
  "Erros comuns no uso do Dialogflow",
  "Implementando chatbots de serviço ao cliente",
  "Como criar conversas interativas",
  "Utilizando modelos pré-treinados",
  "Adicionando personalização ao chatbot",
  "Estratégias de escalabilidade no Dialogflow",
  "Utilizando slots e valores obrigatórios",
  "Criando diálogos contextuais",
  "Monitorando e melhorando o desempenho do chatbot",
  "Como medir a satisfação do usuário",
  "Ferramentas de depuração no Dialogflow",
  "Controlando o fluxo da conversa",
  "Configurações de agentes avançadas",
  "Entidades compostas e hierárquicas",
  "Como ajustar intents para respostas rápidas",
  "Respostas de áudio e voz no Dialogflow",
  "Integrando Dialogflow com Slack",
  "Como criar assistentes virtuais",
  "Gerenciamento de estado de diálogo",
  "Respostas multimodais no Dialogflow",
  "Integração com sistemas de pagamento",
  "Criando bots para ecommerce",
  "Estratégias de testes para chatbots",
  "Melhorando a experiência de onboarding",
  "Definindo respostas empáticas",
  "Ajustando respostas de fallback",
  "Como lidar com conversas fora do escopo",
  "Utilizando webhooks com Dialogflow",
  "Como lidar com múltiplos usuários",
  "Personalizando a experiência de conversação",
  "Gerenciamento de APIs externas",
  "Como criar bots para redes sociais",
  "Aprimorando a escalabilidade dos agentes",
  "Respostas baseadas em sentimentos",
  "Gerenciamento de falhas de entendimento",
  "Como ajustar agentes para setores específicos",
  "Respostas adaptativas com Machine Learning",
  "Testes automatizados para chatbots",
  "Como reduzir ambiguidades nas respostas",
  "Técnicas de NLP avançadas no Dialogflow",
  "Respostas baseadas em localização",
  "Criando chatbots com personalidade",
  "Como tratar dados sensíveis",
  "Usando algoritmos de aprendizado para melhorar diálogos",
  "Implementando fluxos de diálogos não-lineares",
  "Gerenciamento de contexto longo",
  "Aprimorando a precisão das entidades",
  "Respostas baseadas em tempo real",
  "Como ajustar o chatbot para diferentes tons de voz",
  "Conectando Dialogflow com CRMs",
  "Estratégias para lidar com múltiplos canais de comunicação",
  "Como identificar intenção implícita",
  "Automatizando respostas de feedback",
  "Personalizando respostas de voz",
  "Gerenciamento de grandes volumes de dados",
  "Como melhorar o design de conversas",
  "Respostas preditivas no Dialogflow",
  "Utilizando API Gateway com Dialogflow",
  "Como otimizar chatbots para dispositivos móveis",
  "Integrando com sistemas de ERP",
  "Implementação de chatbots para suporte técnico",
  "Estratégias para melhorar engajamento do usuário",
  "Como criar protótipos rápidos no Dialogflow",
  "Melhorando a fluidez da conversa",
  "Respostas personalizadas por segmento de usuário",
  "Como lidar com interrupções durante o diálogo",
  "Gerenciamento de tempos de inatividade",
  "Testando chatbots com grandes volumes de tráfego",
  "Usando big data para melhorar diálogos",
  "Como criar bots baseados em objetivos",
  "Utilizando aprendizado contínuo para aprimorar respostas",
  "Respostas em tempo real usando serviços externos",
  "Técnicas de otimização para processamento de linguagem",
  "Como configurar múltiplos webhooks",
  "Criando fluxos de conversa personalizáveis",
  "Aprimorando reconhecimento de voz em ambientes ruidosos",
  "Como treinar agentes com diálogos naturais",
  "Estratégias de retenção de usuários",
  "Monitoramento de KPIs de desempenho de chatbots",
  "Utilizando aprendizagem supervisionada para respostas",
  "Respostas de texto enriquecido com cards e listas",
  "Personalizando fluxos de conversa por sessão",
  "Como implementar APIs de terceiros",
  "Conectando Dialogflow com soluções de IoT",
  "Gerenciamento de diálogos multicanais",
  "Implementação de chatbots para indústrias específicas",
  "Criando diálogos que simulam conversas humanas",
  "Aprimorando conversas com elementos multimídia",
  "Respostas condicionais avançadas com webhooks",
  "Como criar uma base de conhecimento para o chatbot",
  "Integração com sistemas de notificação",
  "Como ajustar o tempo de resposta do chatbot",
  "Criando fluxos de diálogos dinâmicos",
  "Respostas rápidas baseadas em histórico de conversas",
  "Como criar chatbots educativos",
  "Integrando o Dialogflow com sistemas de IA externos",
  "Respostas automáticas com padrões de conversa",
  "Gerenciamento de dependências externas",
  "Como reduzir a latência nas respostas do chatbot",
];
const saas = [
  "Introdução ao SaaS com Stripe e Supabase",
  "Configurando o ambiente de desenvolvimento com React Native",
  "Integração do Stripe para pagamentos no SaaS",
  "Autenticação de usuários com Supabase",
  "Gerenciamento de usuários no sistema SaaS",
  "Implementando planos de assinatura com Stripe",
  "Interface de usuário para gestão de assinaturas no React Native",
  "Configuração de notificações de pagamento com Stripe",
  "Controle de acesso baseado em planos de assinatura",
  "Automatizando renovações de assinaturas com Stripe",
  "Gerenciamento de faturas no sistema SaaS",
  "Implementando a lógica de downgrade de planos",
  "Criação de relatórios financeiros com Stripe e Supabase",
  "Gerenciando usuários inativos no sistema SaaS",
  "Uso de webhooks do Stripe para monitoramento de pagamentos",
  "Integração de funções de email para o sistema SaaS",
  "Implementando upgrades automáticos de planos com Stripe",
  "Gerenciamento de tokens de autenticação com Supabase",
  "Segurança de dados no SaaS com Supabase",
  "Criação de um dashboard para administradores SaaS",
  "Gestão de convites e permissões no sistema SaaS",
  "Implementando suporte a diferentes métodos de pagamento no Stripe",
  "Uso de gráficos e relatórios no painel de usuário",
  "Gerenciamento de promoções e cupons de desconto no Stripe",
  "Gerenciamento de perfis de usuário no React Native",
  "Autenticação social com Supabase",
  "Controle de reembolsos e cancelamentos no Stripe",
  "Melhorando a UX de pagamento no app com React Native",
  "Integração de notificações push no sistema SaaS",
  "Gerenciamento de times e permissões no SaaS",
  "Criação de um sistema de suporte ao cliente dentro do app",
  "Monitoramento de churn rate com Supabase e Stripe",
  "Automatizando emails de boas-vindas para novos usuários",
  "Acompanhamento de KPIs para negócios SaaS",
  "Estrutura de banco de dados para um sistema SaaS",
  "Melhorando a performance do backend com Supabase",
  "Criando componentes reutilizáveis no React Native",
  "Automatizando cobranças com o Stripe Billing",
  "Gerenciamento de pagamentos atrasados e inadimplentes",
  "Uso de funções assíncronas para processar dados no Supabase",
  "Implementando cache para melhorar a performance do SaaS",
  "Gerenciamento de upgrades de plano em tempo real",
  "Implementando teste A/B para otimizar o funil de vendas",
  "Gerenciamento de afiliados e comissões com Stripe",
  "Criando uma experiência de onboarding perfeita no app",
  "Implementação de autenticação multifatorial com Supabase",
  "Construindo uma página de checkout personalizada com Stripe",
  "Integrando análises de uso com ferramentas externas",
  "Gerenciamento de arquivos de mídia no sistema SaaS",
  "Automatizando processos administrativos com Supabase Functions",
  "Monitoramento em tempo real de transações financeiras no Stripe",
  "Construindo um sistema de feedback do usuário",
  "Implementando um sistema de chat no aplicativo SaaS",
  "Gerenciamento de períodos de teste para novos usuários",
  "Otimização da experiência de renovação de assinatura no app",
  "Implementando políticas de privacidade e termos de uso",
  "Analisando métricas de conversão de usuários no sistema",
  "Criação de uma central de notificações para usuários",
  "Implementando funcionalidade offline no app React Native",
  "Análise de erros e exceções no sistema SaaS",
  "Criação de relatórios de faturamento detalhados com Stripe",
  "Monitoramento de sessões de usuário em tempo real",
  "Desenvolvendo uma interface administrativa para gerenciar planos",
  "Automatizando notificações de expiração de cartão com Stripe",
  "Integrando analytics para monitorar o comportamento dos usuários",
  "Implementando controle de versões para funcionalidades do app",
  "Gerenciamento de armazenamento de dados no Supabase",
  "Monitoramento de KPIs financeiros com Stripe e Supabase",
  "Implementando lembretes automáticos para renovações de plano",
  "Criação de um sistema de recomendação de produtos no app",
  "Gerenciamento de feedback de usuários com Supabase",
  "Uso de testes unitários para garantir a qualidade do SaaS",
  "Implementação de relatórios de uso para administradores",
  "Integração de serviços externos com webhooks do Supabase",
  "Criação de uma arquitetura modular no React Native",
  "Implementação de pagamentos recorrentes no Stripe",
  "Monitoramento de cancelamentos e reembolsos no SaaS",
  "Automatizando o processo de verificação de identidade no Stripe",
  "Gerenciamento de diferentes moedas no sistema de pagamento",
  "Implementando uma estrutura de permissões granulares no SaaS",
  "Uso de tabelas dinâmicas para exibir dados no React Native",
  "Automatizando o processo de cobrança de taxas adicionais",
  "Criação de um sistema de alertas para administradores",
  "Monitoramento de abandono de carrinho no sistema SaaS",
  "Implementando um sistema de recompensas e pontos no app",
  "Uso de animações no React Native para melhorar a UX",
  "Monitoramento de tráfego e uso do app em tempo real",
  "Criação de um sistema de revisões e comentários de usuários",
  "Implementação de um sistema de reservas dentro do SaaS",
  "Gerenciamento de APIs públicas e privadas no SaaS",
  "Automatizando a atualização de dados de usuários com Supabase",
  "Monitoramento de uso de recursos de plano no sistema SaaS",
  "Implementando suporte a diferentes fuso horários no app",
  "Gerenciamento de descontos sazonais com Stripe",
  "Criação de gráficos interativos com dados em tempo real",
  "Implementando uma página de agradecimento após a compra",
  "Criação de relatórios sobre engajamento de usuários",
  "Uso de autenticação biométrica no app com React Native",
  "Implementando uma camada de segurança adicional para pagamentos",
  "Monitoramento de saldo de crédito dos usuários no SaaS",
  "Uso de tecnologia de IA para prever churn rate",
  "Gerenciamento de migração de dados no SaaS",
  "Criação de um sistema de notificações por email e SMS",
  "Monitoramento de atividades suspeitas no sistema SaaS",
  "Implementação de um programa de indicação de usuários",
  "Automatizando o processo de suporte ao cliente",
  "Criação de um sistema de integração com marketplaces",
  "Implementando suporte a pagamentos parcelados no Stripe",
  "Gerenciamento de diferentes perfis de administrador",
  "Uso de criptografia para proteger dados sensíveis",
  "Criação de uma API para integração com serviços de terceiros",
  "Gerenciamento de conexões de rede no React Native",
  "Monitoramento de acessos simultâneos no sistema SaaS",
  "Uso de gráficos de barras e linhas para visualização de dados",
  "Implementando relatórios detalhados de uso do sistema",
  "Criação de um sistema de auditoria no SaaS com Supabase",
  "Monitoramento de pagamentos bem-sucedidos e falhos",
  "Implementando um sistema de recomendação de planos personalizados",
  "Gerenciamento de diferentes níveis de permissão para times",
  "Automatizando processos de atualização de planos de assinatura",
  "Criação de formulários inteligentes com validação em tempo real",
  "Implementando uma landing page otimizada para SEO no SaaS",
  "Monitoramento de integrações com serviços externos",
  "Automatizando a geração de faturas e recibos com Stripe",
  "Criação de um sistema de consulta de saldo para administradores",
  "Gerenciamento de domínios personalizados no SaaS",
  "Monitoramento de relatórios de erro no backend com Supabase",
  "Implementando integração com redes sociais no React Native",
  "Automatizando o suporte a clientes com chatbots",
  "Criação de um sistema de busca avançada no SaaS",
];
const capitulosNodeJS = [
  "Introdução ao Node.js",
  "Instalação e Configuração",
  "Conceitos Fundamentais do Node.js",
  "Trabalhando com Módulos",
  "Sistema de Arquivos (fs)",
  "Fluxos de Dados (Streams)",
  "Buffers e Manipulação de Dados Binários",
  "Eventos e EventEmitter",
  "Timers no Node.js",
  "Utilizando Console e Debug",
  "Manipulação de Processos",
  "NPM: Gerenciador de Pacotes",
  "Módulos Core",
  "Entendendo o Asynchronous Programming",
  "Callbacks e Promises",
  "Async/Await",
  "HTTP: Servidor e Cliente",
  "HTTPS e Certificados",
  "Módulo Net: TCP/UDP",
  "Sockets e WebSockets",
  "Fastify: Framework de Aplicações Web",
  "Roteamento em Fastify",
  "Middlewares em Fastify",
  "Tratamento de Erros",
  "Manipulação de Requisições HTTP",
  "Respostas HTTP",
  "Cookies e Sessões",
  "Autenticação e Autorização",
  "API RESTful com Node.js",
  "Trabalhando com GraphQL",
  "Integração com Bancos de Dados",
  "MongoDB e Mongoose",
  "MySQL com Node.js",
  "PostgreSQL com Node.js",
  "SQLite com Node.js",
  "NoSQL vs SQL",
  "Tratamento de Arquivos com Multer",
  "Upload de Arquivos",
  "Gerenciamento de Cache com Redis",
  "Memcached no Node.js",
  "Filas e Processamento Assíncrono",
  "Mensageria com RabbitMQ",
  "Log e Monitoramento",
  "Gerenciamento de Sessões",
  "Proteção contra Ataques CSRF",
  "Injeção de Dependências",
  "Testes Unitários com Mocha e Chai",
  "Testes de Integração",
  "Testes Funcionais",
  "Mocking em Testes",
  "Depuração de Aplicações Node.js",
  "Gerenciamento de Erros",
  "Logs Personalizados",
  "Gerenciamento de Memória",
  "Stream de Dados com WebSockets",
  "Sincronização de Dados em Tempo Real",
  "Configuração de Variáveis de Ambiente",
  "Docker e Contêineres com Node.js",
  "Deploy em Servidores VPS",
  "Deploy no Heroku",
  "Deploy no AWS",
  "Deploy no Google Cloud",
  "CI/CD com Node.js",
  "Integração com Jenkins",
  "Integração com Travis CI",
  "Automação de Testes",
  "Monitoramento de Performance",
  "Otimização de Aplicações Node.js",
  "Segurança em Aplicações Node.js",
  "Proteção contra Injeção de SQL",
  "Validação de Dados de Entrada",
  "Gerenciamento de Usuários",
  "Criptografia e Hashing",
  "Envio de E-mails com Node.js",
  "Integração com APIs Externas",
  "Autenticação OAuth2",
  "Integração com Firebase",
  "Notificações Push",
  "Serviços em Tempo Real",
  "Microservices com Node.js",
  "Event-Driven Architecture",
  "GraphQL Subscriptions",
  "Escalabilidade Horizontal",
  "Load Balancing",
  "Clusterização de Processos",
  "Distribuição de Carga",
  "Gerenciamento de Threads",
  "Worker Threads",
  "Node.js em Plataformas Móveis",
  "Uso de Node.js com IoT",
  "Aplicações Híbridas com Node.js",
  "Streams de Mídia em Tempo Real",
  "Server-Side Rendering com Node.js",
  "Comparação Node.js vs Deno",
  "Comparação Node.js vs Bun",
  "Padrões de Projeto com Node.js",
  "Monitoramento com PM2",
  "Trabalhando com Clusters",
  "Aplicações Real-Time com Socket.io",
  "Processamento em Lote",
  "Transmissão de Mídia em Tempo Real",
  "Geração de Relatórios com Node.js",
  "Node.js e Machine Learning",
  "Automatização de Tarefas",
  "Task Schedulers com Node.js",
  "Utilização de Cron Jobs",
  "Aprimoramento de Desempenho",
  "Comparação de Bibliotecas Node.js",
  "Gerenciamento de Dependências",
  "Uso de Configurações Dinâmicas",
  "Trabalhando com YAML",
  "Sistemas de Logs Distribuídos",
  "Tracing e Diagnóstico de Erros",
  "Manutenção e Atualizações do Node.js",
  "Boas Práticas de Segurança",
  "Contribuição para o Core do Node.js",
  "Node.js e WebAssembly",
  "Node.js e Blockchain",
  "Node.js para Ciência de Dados",
  "Integração com Hadoop e Big Data",
  "Criação de Ferramentas CLI",
  "Distribuição de Aplicações Node.js",
  "Atualizações no Ecossistema Node.js",
  "Tendências Futuras do Node.js",
  "Comparação com Outros Frameworks",
  "Desenvolvimento de Ferramentas Open Source",
  "Construção de Produtos SaaS com Node.js",
  "Integração com Ferramentas de DevOps",
  "Análise de Performance com Node.js",
  "Lidando com Streams de Dados",
  "Streaming de Vídeo com Node.js",
  "Real-Time Chat Application com Node.js",
  "Integração com Blockchain",
  "Node.js em Cloud Functions",
  "Case Studies de Sucesso com Node.js",
  "Migrando para a Última Versão do Node.js",
  "Explorando o Node.js LTS",
  "Node.js em Ambientes Multithread",
  "Estendendo Funcionalidades com Addons Nativos",
  "Builds Customizados do Node.js",
  "Node.js em Ambientes Sem Servidor (Serverless)",
  "Execução de Funções Lambda com Node.js",
  "Integração com Kubernetes",
  "Node.js em Ambientes Distribuídos",
];
